### ISSUE TITLE
rpgleIndentationEnabled Gone?

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#15]
Where did "code-for-ibmi.rpgleIndentationEnabled": true go? I know it was experimental, but I liked the feature ! And it worked fairly recently, now it is "unknown Configuration setting". In fact, per #387, it looked like it would be handy to totally fix indention.

I don't can't see any references here. Only this:

Enable these options in VS Code settings.

vscode-rpgle.rpgleColumnAssistEnabled - column assist for RPGLE fixed-format.
    vscode-rpgle.rpgleColumnAssistant / Shift+F4 to launch it when on fixed-format line
vscode-rpgle.rpgleContentAssistEnabled - shows content assist and enables the following commands
    vscode-rpgle.rpgleOpenInclude / Shift+F12 when on copy or include statement
vscode-rpgle.rpgleLinterSupportEnabled - enables linter
    vscode-rpgle.openLintConfig to open or create linter file. Creates / opens relative to source that is currently open. Read more below on linting.

I have 0.0.4 of the extension installed, but get some (inconsistent) messages and squiggly line on indentation. Couple of examples:
![image](https://user-images.githubusercontent.com/67484051/142947715-81b58357-dc3e-476e-9ddc-cac046c783dd.png)
![image](https://user-images.githubusercontent.com/67484051/142947208-c037637c-b500-4d8b-9ecf-516691ea7285.png)

**Comment by worksofliam** [comment]
Hey @SJLennon - sorry, I don't really understand what the question is here.

Could you clarify for me?

**Comment by worksofliam** [comment]
@SJLennon Having re-read it a few times, please feel free to share a snippet of code you're having issues with.

This is a fairly large change, I'm aware. Once we get the kinks worked out after migrating all the code, it will be great.

**Comment by SJLennon** [comment]
@worksofliam Well, let me try to clarify...
1) There is  nothing about indentation in the readme.  (That I can see.)
2) If I don't want it there is not a way to turn it off. (Not that I want to turn it off if it works, but someone might.)
3) The "quick fixes" you added recently no longer seem to work.
4) It appears inconsistent in when it checks for and how it reports errors.

I started this comment before your prior response about a "fairly large change" appeared.  1. and 2. and 3. still apply.  For 4. lets work with this.

I just opened code that was previously saved and it seems to be  correct in reporting the errors:
![image](https://user-images.githubusercontent.com/67484051/142968060-6488894d-1057-4b27-b832-2aa88e0a98f7.png)

I have attached that file as LOG.txt. (The code does compile but is largely just a demonstration.)

If I correct line 22, by removing all the leading blanks and then inserting a tab, I get this:
![image](https://user-images.githubusercontent.com/67484051/142968250-7d32d6a5-0b62-44b6-8098-d0cdcc9681c4.png)

Note that there is a squiggle in line 22 under the "J" and the PROBLEMS tab still says "got 12" for line 22.

If I insert after line 26, it doesn't notice that the indentation is incorrect:
![image](https://user-images.githubusercontent.com/67484051/142968525-c0abfd69-cc67-4e22-850f-cb0219ec2c20.png)
Hope this helps.

Even if I correct line 26
[LOG.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7585720/LOG.txt)

**Comment by worksofliam** [comment]
@SJLennon It seems to be working for me.

I tried your code, it was showing the correct indentation warnings and I also was able to get it to react to another validation error.

![image](https://user-images.githubusercontent.com/3708366/142970078-951dc221-5eef-4fee-b6b7-ed6a23797219.png)

This is on 0.0.5.

**Comment by SJLennon** [comment]
@worksofliam 0,0,5 makes no difference. 
1. I've restarted VS Code multiple times just to be sure I always have a clean environment.
2. I've uninstalled the extension, restarted VS Code to see that there is no indentation checking, re-installed the extension. No difference.
3. I created a brand new connection.  Still no success, other than it didn't ask me to install the Cl Prompting tools, which my my other two connections always do.

Perhaps there is some other extension that is conflicting with it.
Or perhaps I have something odd in my settings.json.  I may try removing all code for ibm i stuff from setting.json and just start over.  Or maybe I'll try installing VS Code in a virtual machine and start clean there.

**Comment by worksofliam** [comment]
@SJLennon what version of Code for IBM i do you have? Perhaps an old version if conflicting with it.

Honestly, I am still lost at what your issue is. Sorry about that.

Are the errors not over the right columns? Are certain errors not appearing?

**Comment by SJLennon** [comment]
I'm on the latest version of everything.  Living on the bleeding edge...
Code for IBM i 0,8,2
VS Code 1.62.3

**Comment by SJLennon** [comment]
**No success with a brand new installation** 
So is the problem Windows, or is it PUB400?  Is it me?  Thoroughly confused ☹️ .

**The details:**
Running under VMware and Win 10. Win 10 up to date.  
First time installation of VS Code in this VM.  No customization other than to pick the theme  (stttings.json provided belwo).
Only 4 extensions installed.
![image](https://user-images.githubusercontent.com/67484051/143092340-3788ddcf-ff9f-4c00-a8eb-ba3efae1af46.png)

Created new connection. Opened source, got errors as expected:
![image](https://user-images.githubusercontent.com/67484051/143092863-81d011c7-f5e4-4093-b529-2f13146f33ba.png)

Deleted leading spaces on line 22. Still has squiggles. 
Fixed line 26.  Still has squiggles.
Inserted after line 26.  New line 27 has no indication of error.
Problem tab has not changed.
![image](https://user-images.githubusercontent.com/67484051/143094131-6f8c90bf-dc2c-45e9-801c-27c146afe1b7.png)

Shorter version of test code:
[LOG.TXT](https://github.com/halcyon-tech/vscode-rpgle/files/7590814/LOG.TXT)
Settings.json:
```
{
    "workbench.colorTheme": "Visual Studio Dark",
    "code-for-ibmi.connectionSettings": [
        {
            "name": "tPub400",
            "objectFilters": [
                {
                    "name": "temp",
                    "library": "LENNONS1",
                    "object": "TEMP",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "undefined": "temp"
                }
            ],
            "databaseBrowserList": [
                "LENNONS1",
                "LENNONS2",
                "QTEMP",
                "QGPL"
            ],
            "libraryList": [
                "LENNONS1",
                "LENNONS2",
                "QTEMP",
                "QGPL"
            ],
            "customVariables": [],
            "connectionProfiles": [],
            "ifsShortcuts": [
                "/home/LENNONS"
            ],
            "homeDirectory": "/home/LENNONS",
            "tempLibrary": "LENNONS1",
            "currentLibrary": "LENNONS1",
            "sourceFileCCSID": "*FILE",
            "enableSQL": true,
            "hideCompileErrors": [],
            "enableSourceDates": false,
            "sourceDateLocation": "none",
            "clContentAssistEnabled": false,
            "autoSaveBeforeAction": false
        }
    ],
    "code-for-ibmi.connections": [
        {
            "name": "tPub400",
            "host": "pub400.com",
            "port": 2222,
            "username": "lennons",
            "privateKey": null
        }
    ]
}
```
@worksofliam

**Comment by SJLennon** [comment]
@worksofliam Spent the evening building a Ubuntu VM.  Installed VS Code.  
Just connected to PUB400.  Opened source and it **seems** to have the same problems.  More experimentation in the morning...

**Comment by SJLennon** [comment]
@worksofliam Spent the evening building a Ubuntu VM.  Installed VS Code.  
Just connected to PUB400.  Opened source and it **seems** to have the same problems.  More experimentation in the morning...

**Comment by worksofliam** [comment]
@SJLennon You next best thing to do is a get a video recorded for me.

**Comment by SJLennon** [comment]
@worksofliam Can you suggest the best software to record a video? (Presumably you mean recording the screen, because I don't have a camera of mike on this desktop.)

**Comment by SJLennon** [comment]
@worksofliam   
**I have new findings** It seems like a switch to another tab, then switching back causes a rerun of the indentation logic.
 
I've replicated the problem on my Win 10 desktop, in Ubuntu in a VM, and today in a new installation of VS Code on my Win 10 laptop. So I don't think the issue lies is my hardware, OS or my VS Code configuration.  So I did some more testing and stumbled into this;

I have two files, **A_ERR** which has two indentation errors and **A_OK** which has no errors.

My test script:

1. Start VS Code and connect to PUB400.COM
2. Open a source file that contains A_ERR and A_OK.
3. Clear Code for IBM i output.
4. Open A_ERR.  (Code for IBM i output shows member being copied twice to the IFS.  Don't know if this is significant or normal.)
5. In A_ERR there are errors at line 22, line 26, and in the PROBLEMS tab.
6. Fix the error at line 26.  Errors still show on line 26 and in the PROBLEMS tab.
7. Open A_OK.  (Two copies again from member to IFS.)
8. A_OK has no errors in it.
9. Switch back to the tab with A_ERR. Now line 26 shows no errors, line 22 still has an error, and the PROBLEMS tab shows just the line 22 error.
10. Fix the line 22 error. Nothing changes, error still show on line 22 and in the PROBLEMS tab.
11. Switch to A_OK,
12. Switch back to A_ERR. Now it has no errors shown and there is nothing in the PROBLEMS tab.

After some more experimentation, it doesn't seem to matter that the second tab is RPGLE or something else, or if it has errors or not. It seems like switching away from the tab with errors and switching back to it corrects the indentation errors.

I'm curious about the copy from source member to IFS.  

1. If I switch tabs between A_OK and A_ERR without making any changes I see the copy taking place each time. I assume this is normal.  
2. But when I make a correction to A_ERR, and switch to A_OK, I see A_OK being copied.. But when I switch back to A_ERR no copy takes place.  
3. In fact, once I've fixed A_ERR, switching between tabs always causes a copy for A_OK but never for A_ERR. Which, to me, seems odd.

My test files, in case they are useful;
[A_ERR.TXT](https://github.com/halcyon-tech/vscode-rpgle/files/7600069/A_ERR.TXT)

[A_OK.TXT](https://github.com/halcyon-tech/vscode-rpgle/files/7600065/A_OK.TXT)

**Comment by worksofliam** [comment]
@SJLennon Just want you to know this is on my priority list after I am done working on another Code for IBM i bug.

Will get back to this ASAP.

**Comment by SJLennon** [comment]
@worksofliam Appreciate the update and your efforts. 
I'm not inconvenienced.  Handle things that impact most users first.

**Comment by worksofliam** [comment]
@SJLennon Good news!! I finally recreated this issue.

I think I know the cause... will post again when I am able to work on it.

**Comment by worksofliam** [comment]
@SJLennon I just released 0.0.7 - will you give it another go?

**Comment by SJLennon** [comment]
@worksofliam I just did a quick test with 0.0.7 and VS Code 0.8.4.
1, Now I'm not seeing any errors in A_ERR.  I can't do anything to show an indentation error.  Is there any new setting I need to turn on?

2. In Code for IBM i OUTPUT, when I open the member,  I still see A_ERR and A_OK being copied twice to the IFS.
However, when I switch between tabs I no longer see the source being copied to the IFS (as was happening before--see a., b., c. comments above).

Maybe it's late...

**Comment by SJLennon** [comment]
@worksofliam Also noticed today that I need to have RPGLE Language Tools installed to get content assist (%subst, etc) to work.

**Comment by worksofliam** [comment]
@SJLennon 

1. Do you have the linter enabled in the VS Code settings?
2. Yes, the snippets were moved to this language extension from the base.

**Comment by SJLennon** [comment]
@worksofliam 
Setting  **"vscode-rpgle.rpgleLinterSupportEnabled":true,** seems to be the trick.  Looks to be working fine now. 

Sorry, I would not have expected that this would be considered part of lint, which was something that I planned to look at when it stabilized a bit more.

**Comment by worksofliam** [comment]
Yes, there were some issues with the linter when it was disabled and it still working.

What do you say the status of your issue is now?

**Comment by SJLennon** [comment]
@worksofliam 
Didn't I see that on an indentation error it would offer a quick fix?  That seems to have gone.

**Comment by worksofliam** [comment]
@SJLennon thar actually was purposed removed for now (for some technical reasons, though I do miss it). Perhaps that'd be worth another issue!

**Comment by SJLennon** [comment]
I'll beat it around a bit tomorrow.
________________________________

**Comment by SJLennon** [comment]
@worksofliam Looks like everything is good now.  Closing.
